### PR TITLE
increase ansi-styles version

### PR DESCRIPTION
**Pull request by willricardo**
Increase ansi-styles version to 2.2.1 to fix the follow error.:

```npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

### CODE REVIEW

**Comment by cthorne66** [comment]
Isn't there a corresponding chalk version update in package.json to solve for this?

**Comment by vovchenso** [comment]
I don't think so. You need to generate new npm-shrinkwrap.json to solve the issue. It works now if you install the package with --no-shrinkwrap flag.

**Comment by willricardo** [comment]
Only update chalk version dont work, because in the npm-shrinkwrap.json the specific versions was set and increase chalk version don't update this.

If you install the package with --no-shrinkwrap, it's works fine because in the chalk dependencies the version of ansi-styles was set to "^2.1.0".

To remove chalk definitions in npm-shrinkwrap.json, we need to do a lot of tests.

**Comment by cthorne66** [comment]
I believe the most straight forward ways to achieve the fix is to remove the shrinkwrap file, update dependencies until the desired behaviors are in place, then regenerate the shrinkwrap file.

Or, update the dependencies to more specific versions, and remove the need for a shrinkwrap.  

Either are acceptable, but not modifying the shrinkwrap file directly please

**Comment by willricardo** [comment]
I agree with you, this isn't better way to fix. I needed fix this ASAP, because my build CI was broken today and I didn't have time to fix more better.
I'll close my pull request and later I'll open with better fix.
thanks a lot.

**Pull request closed without merging**
